bpcreech/PyMiniRacer

README.md
The README doesn't yet link to the docs. I found these via the blog entry: https://bpcreech.com/post/mini-racer/
=> Link to documentation from README

src/v8_py_frontend/binary_value.cc, src/v8_py_frontend/binary_value.h, src/v8_py_frontend/code_evaluator.cc, src/v8_py_frontend/code_evaluator.h, src/v8_py_frontend/heap_reporter.cc, src/v8_py_frontend/mini_racer.cc, tests/test_eval.py
I copied in the logic from the d8 tool (part of the v8 repo), resulting in slightly better exception reports.
I also moved this into `binary_value.h` for easier reuse in future work to expose JS Promises to Python.
=> Move and improve exception logic

HISTORY.md, README.md, pyproject.toml, src/py_mini_racer/py_mini_racer.py, tests/test_eval.py
This is a partial rollback of https://github.com/bpcreech/PyMiniRacer/pull/8 which was never released.
That PR did two main things:
* Make execution within the DLL return results via callbacks to Python instead of blocking interminably, and
* Support optional Python `asyncio` mode, offloading waiting-on-the-DLL from the asyncio event loop.
On further thought, I think the latter isn't quite necessary. For now you can use `asyncio` with PyMiniRacer easily enough, using [`loop.run_in_executor()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) to offload work from the asyncio event loop as with any other long-running synchronous code. Later, I plan to add support for JS Promises, which will let you offload work even from the JS main thread by writing …
=> Remove not-yet-released Python async methods

src/v8_py_frontend/task_runner.cc, src/v8_py_frontend/task_runner.h
In some follow-on work I noticed we were doing extra copies and [this excellent blog post](https://taylorconor.com/blog/noncopyable-lambdas/) explains why. (TL;DR: Using std::function forces the compiler to copy data to coerce the type of the lambda from an anonymous closure to a std::function.)
Ideally this PR would have unit tests, but, welp, we don't have a C++ unit test framework set up in PyMiniRacer yet, so for now it's just an untested performance optimization. In a follow-on commit it will probably become a requirement for things to compile (because copying enclosed functor params isn't always possible).
=> Remove extra copying of task functors

CONTRIBUTING.md, HISTORY.md, helpers/v8_build.py
[An out-of-band update to `mdformat_mkdocs`](https://github.com/KyleKing/mdformat-mkdocs/issues/20) has caused it to *stop* putting weird extra spaces on the end of list items.
Also, an unrelated Python formatting nit that I had force-pushed because, apparently, 🤠.
=> Format docs with new mdformat_mkdocs

CONTRIBUTING.md, pyproject.toml, src/py_mini_racer/__init__.py, src/py_mini_racer/py_mini_racer.py, src/v8_py_frontend/BUILD.gn, src/v8_py_frontend/binary_value.cc, src/v8_py_frontend/binary_value.h, src/v8_py_frontend/callback.h, src/v8_py_frontend/exports.cc, src/v8_py_frontend/isolate_holder.cc, src/v8_py_frontend/mini_racer.cc, src/v8_py_frontend/mini_racer.h, src/v8_py_frontend/promise_attacher.cc, src/v8_py_frontend/promise_attacher.h, tests/test_eval.py
Works by either:
```python
assert mr.eval("Promise.resolved(42)").get() == 42  # blocks until done
```
or in an `async` function:
```python
assert await mr.eval("Promise.resolved(42)") == 42  # yields the coroutine until done
```
I didn't put an example yet in the docs (i.e., `README.md`) because, awkwardly, there's not a good and simple way to actually make a Promise worth demoing. The usual thing is `setTimeout` but we don't have a `setTimeout` yet. I'll work on that next.
In the meanwhile this could be useful for moving CPU-intensive work off the main thread.
=> Add support for JS Promises

src/py_mini_racer/py_mini_racer.py, src/v8_py_frontend/binary_value.cc, src/v8_py_frontend/binary_value.h, src/v8_py_frontend/exports.cc, src/v8_py_frontend/isolate_manager.cc, src/v8_py_frontend/mini_racer.cc, src/v8_py_frontend/mini_racer.h, src/v8_py_frontend/object_manipulator.cc, src/v8_py_frontend/object_manipulator.h, src/v8_py_frontend/promise_attacher.cc, src/v8_py_frontend/promise_attacher.h
Several related things:
1. Instead of passing raw `v8::Persistent` pointers from C++ to Python, store a mapping from `BinaryValue*` object IDs `v8::Persistent` in the `BinaryValueFactory` from C++ to Python, similarly to how `ArrayBuffer`s already work. This simplifies the Python side (it can refer to Objects using the `BinaryValue` pointer *only*, rather than maintaining a `BinaryValue` pointer for memory-management purposes and a `v8::Persistent` pointer for actual API calls).
2. When freeing `v8::Persistent` pointers *and* `ArrayBuffer` `backing_store` instances, do so on the isolate message pump. This was probably a thread safety bug. (I didn't see any crashes, and the documentation doesn't say whether you can `delete v8::Persistent<...>` or decref your `backing_store` handle without …
=> Improve safety of creating and freeing BinaryValues

src/py_mini_racer/py_mini_racer.py, src/v8_py_frontend/BUILD.gn, src/v8_py_frontend/binary_value.cc, src/v8_py_frontend/binary_value.h, src/v8_py_frontend/count_down_latch.cc, src/v8_py_frontend/count_down_latch.h, src/v8_py_frontend/isolate_manager.cc, src/v8_py_frontend/isolate_manager.h, src/v8_py_frontend/mini_racer.cc, src/v8_py_frontend/mini_racer.h
Two things:
1. Remove reliance on `__del__` for freeing binary values, because it doesn't always happen in the right order (which in follow-on work, was segfaulting in the tests). Now, `__del__` is only an optional nice-to-have release of memory, and the `MiniRacer::Context` will delete any dangling binary values when it exits.
2. Make sure `MiniRacer::Context` shutdown is orderly wrt async tasks. Before it was possible (never saw it happen, but possible) for Python to start an `eval` task, then start destructing the `Context` before the `eval` gets going, resulting in dangling references to `Context` internals. This is no longer possible because the `Context` awaits any pending async tasks before commencing teardown.
This lets us remove half of the comment in …
=> Fix teardown bugs

HISTORY.md, README.md, src/py_mini_racer/py_mini_racer.py, src/v8_py_frontend/code_evaluator.cc, src/v8_py_frontend/code_evaluator.h, src/v8_py_frontend/exports.cc, src/v8_py_frontend/mini_racer.cc, src/v8_py_frontend/mini_racer.h, src/v8_py_frontend/object_manipulator.cc, src/v8_py_frontend/object_manipulator.h, tests/test_eval.py, tests/test_functions.py
This also removes an old optimization related to simple, no-argument functions in the `eval` method. See update to HISTORY.md for rationale.
=> Add ability to directly call JS functions from Python

src/py_mini_racer/py_mini_racer.py, src/v8_py_frontend/callback.h, src/v8_py_frontend/exports.cc, src/v8_py_frontend/mini_racer.cc, src/v8_py_frontend/mini_racer.h, src/v8_py_frontend/promise_attacher.cc, src/v8_py_frontend/promise_attacher.h
In the cases where the C++ side needs to call back into Python (for all `eval` operations, as well as `Promise` callbacks), we have been using [the `ctypes` `py_object` feature](https://docs.python.org/3/library/ctypes.html#ctypes.py_object), which automatically wraps Python objects as they're passed in and out of the native (C/C++) side.
The `ctypes` `py_object` feature does some spooky undocumented magic related to `PyObject` reference counting. This is discussed briefly [on this StackOverflow](https://stackoverflow.com/questions/52967133/python3-ctypes-callback-causes-memory-leak-in-simple-example) but is not in [the `ctypes` docs](https://docs.python.org/3/library/ctypes.html). What it does works for us for now: every pass-in from Python to C++ increments the `PyObject` count, and …
=> Switch from py_object ptrs to uint64_t callback IDs

src/py_mini_racer/py_mini_racer.py, tests/test_babel.py, tests/test_call.py, tests/test_eval.py, tests/test_functions.py, tests/test_heap.py, tests/test_init.py, tests/test_objects.py, tests/test_strict.py, tests/test_types.py, tests/test_wasm.py
Just cleaning out the parts of the Python `MiniRacer` class which aren't intended for use by `PyMiniRacer` users, so it's easier to understand.
This reduces the amount of time I have to turn off the `SLF001` check in production code, although it intentionally increases it in the test code (because I intentionally want to hide the memory-collection-verification API from ordinary `PyMiniRacer` users; it's just a hack for tests).
=> Move internal Python stuff to a _Context class

src/v8_py_frontend/isolate_manager.cc, tests/test_eval.py
This resolves a bug which I think was introduced in v0.8.1. If you run a long enough microtask without this change, it segfaults Python. Before then, I think the microtask would have simply not run at all (because there was no ongoing loop which ran delayed microtasks).
=> Fix crash on longer-running microtasks

src/v8_py_frontend/isolate_manager.cc, tests/test_eval.py
This resolves a bug which I think was introduced in v0.8.1. If you run a long enough microtask without this change, it segfaults Python. Before then, I think the microtask would have simply not run at all (because there was no ongoing loop which ran delayed microtasks).
(Take 2 on this PR, I just accidentally force-pushed over [Take 1](https://github.com/bpcreech/PyMiniRacer/pull/28). Need to protect the main branch!)
=> Fix segfault on longer microtasks

.pre-commit-config.yaml, src/py_mini_racer/py_mini_racer.py, src/v8_py_frontend/exports.cc, tests/test_init.py
It's actually not quite trivial to answer [this question](https://github.com/bpcreech/PyMiniRacer/issues/25) about whether the V8 Sandbox is enabled on all platforms because the V8 build and runtime have lots of little gates on its enablement. So here's a test we can run a part of CI to assert that it's enabled on all target platforms.
=> Verify the v8 sandbox is enabled

src/py_mini_racer/py_mini_racer.py, src/v8_py_frontend/context.cc, src/v8_py_frontend/context.h, src/v8_py_frontend/context_factory.cc, src/v8_py_frontend/context_factory.h, src/v8_py_frontend/exports.cc, src/v8_py_frontend/exports.h, src/v8_py_frontend/promise_attacher.cc, src/v8_py_frontend/promise_attacher.h
We were passing the same callback function pointer from Python to C++ over and over.
This moves to just passing the callback function pointer once during Context initialization. This makes it a bit simpler and easier to understand (and document!) the object lifecycle requirements.
=> Move to one callback function per Context

README.md
I realized I wrote this wrong... PyMiniRacer currently requires glibc 2.31 on glibc Linux (because it lets V8 use its download of the Debian bullseye sysroot). RHEL and Rocky 8 is still on glibc 2.28, whereas RHEL and Rocky 9 are on glibc 2.34.
(Verified it works on Rocky 9 and fails on Rocky 8 by pulling and running the latest PyMiniRacer wheel from PyPI on an official Rocky container.)
=> Fix advertised RHEL version

.pre-commit-config.yaml, src/v8_py_frontend/js_callback_maker.cc, src/v8_py_frontend/js_callback_maker.h
https://github.com/bpcreech/PyMiniRacer/pull/46 was meant to make the on-the-fly callback system, currently only used by promises, generate callbacks which are reusable for more than one call.
That PR worked on the Python side, but I forgot about the `CallbackHandler` on the C++ side: it is destroyed after first use.
This PR removes `CallbackHandler`, baking the one thing it needed, the callback ID, into a JS object.
=> Make callbacks actually reusable

src/v8_py_frontend/BUILD.gn, src/v8_py_frontend/cancelable_task_runner.cc, src/v8_py_frontend/cancelable_task_runner.h, src/v8_py_frontend/context_factory.cc, src/v8_py_frontend/context_factory.h, src/v8_py_frontend/id_maker.h, src/v8_py_frontend/js_callback_maker.cc, src/v8_py_frontend/js_callback_maker.h
This takes a recurring pattern of turning C++ objects into `uint64_t`s, and generalizing it, using it in 3 places.
We could in theory use this in `BinaryValueFactory` too, but that would be a bit more work as it would change the Python/C++ interface.
=> Generalize ID generation

src/v8_py_frontend/binary_value.cc, src/v8_py_frontend/binary_value.h, src/v8_py_frontend/callback.h, src/v8_py_frontend/context.cc, src/v8_py_frontend/context.h, src/v8_py_frontend/js_callback_maker.cc, src/v8_py_frontend/js_callback_maker.h
Before `BinaryValueFactory` had two missions: creating `BinaryValue`s with a special deleter in them, and remembering the `BinaryValue`s when exchanging them back to Python.
There was one case we didn't want the latter (canceled tasks) requiring special logic there to forget unwanted values. Also, combining these jobs was sort of confusing because you'd get a `shared_ptr<BinaryValue>` back from `BinaryValueFactory::New` which *wouldn't actually delete the object upon its own* (because the factory was saving its own `shared_ptr` reference as a side effect of value creation).
Now we explicitly "Remember" `BinaryValue`s when returning them to Python (as `BinaryValueHandle`s), using a new class, the `BinaryValueRegistry`.
=> Separate out rememberance of BinaryValues

hatch_build.py, helpers/babel.py, src/py_mini_racer/_context.py, src/py_mini_racer/_mini_racer.py, src/py_mini_racer/_types.py, src/py_mini_racer/_value_handle.py, src/v8_py_frontend/context.h, src/v8_py_frontend/context_holder.cc, src/v8_py_frontend/isolate_manager.cc, src/v8_py_frontend/isolate_manager.h, src/v8_py_frontend/isolate_memory_monitor.cc, tests/test_babel.py, tests/test_call.py, tests/test_eval.py, tests/test_functions.py, tests/test_init.py, tests/test_py_js_function.py, tests/test_types.py
`test_interrupts_background_task_on_shutdown` contains an example infinite-loop microtask which would (without this change) prevent MiniRacer from ever exiting.
This also adds an explicit `close` and context manager around `MiniRacer` on the Python side, which would have been nice to have already, and is useful here to write the unit test.
=> Fix freeze on shutdown with eternal microtasks

.github/workflows/build.yml, CONTRIBUTING.md
This is so we can do hotfixes of existing releases without either perfecting or reverting the stuff on main.
=> Switch from tags to branches for releases

src/v8_py_frontend/cancelable_task_runner.cc, src/v8_py_frontend/cancelable_task_runner.h, src/v8_py_frontend/code_evaluator.cc, src/v8_py_frontend/code_evaluator.h, src/v8_py_frontend/context.cc, src/v8_py_frontend/context.h, src/v8_py_frontend/context_holder.cc, src/v8_py_frontend/context_holder.h, src/v8_py_frontend/heap_reporter.cc, src/v8_py_frontend/heap_reporter.h, src/v8_py_frontend/id_maker.h, src/v8_py_frontend/isolate_manager.cc, src/v8_py_frontend/isolate_manager.h, src/v8_py_frontend/isolate_memory_monitor.cc, src/v8_py_frontend/isolate_memory_monitor.h, src/v8_py_frontend/isolate_object_collector.cc, src/v8_py_frontend/isolate_object_collector.h, src/v8_py_frontend/js_callback_maker.cc, src/v8_py_frontend/js_callback_maker.h, src/v8_py_frontend/object_manipulator.cc, src/v8_py_frontend/object_manipulator.h, tests/test_init.py
We were sometimes leaking isolates on shutdown because of reference cycles. In particular, the `IsolateManager` could be running a perpetual (or self-restarting) task which contains `shared_ptr` references to objects which in turn contain `shared_ptr` references to the `IsolateManager`.
This makes simplifies the lifecycle of most things in the C++ side of `PyMiniRacer`. Instead of using `shared_ptr` to manage lifecycle, we more explicitly manage lifecycles. Any classes which send tasks to the `IsolateManager` are, obviously, responsible for ensuring those tasks complete before the classes are destructed. `IsolateManager::Run` now returns a `future` to make that easier to do.
Closes https://github.com/bpcreech/PyMiniRacer/issues/62.
=> Fix isolate leak on teardown

HISTORY.md, src/py_mini_racer/__about__.py, src/py_mini_racer/_context.py, src/py_mini_racer/_objects.py, tests/test_py_js_function.py
Before this change, `wrap_py_function` could tear down the JS callback function and stop processing callbacks, but then receive straggling callbacks that were still being transported from the V8 thread to the asyncio event loop thread. It would then the queue-accounting logic would wait on those last straggling callbacks and never finish them, since it had already torn down the processing task.
Now we may still create tasks for straggling callbacks, but then we'll consistently drop those tasks if we've already stopped processing pending items.
This also gets rid of the use of `asyncio.Queue` which I realized wasn't making anything easier. (I want it to be a golang channel, but it isn't!)
=> Fix racey hang while unwinding wrap_py_function
